### ISSUE TITLE
Expand only one cell?

### ISSUE THREAD

**Issue by jboteros** [tadija/AEAccordion#5]
@tadija Is it possible to expand only one cell and automatically close the previously expanded cell (if there is one)?

Thanks!!!

**Comment by iStorry** [comment]
>     open func toggleCell(_ cell: AccordionTableViewCell, animated: Bool) {
        if cell.expanded {
            collapseCell(cell, animated: animated)
        } else {
            if expandedIndexPaths.count > 0 {
                for i in 0 ..< expandedIndexPaths.count {
                    if let cellPath = tableView.cellForRow(at: self.expandedIndexPaths[i]) {
                        collapseCell(cellPath as! AccordionTableViewCell, animated: animated)
                    }
                }
            }
            expandCell(cell, animated: animated)
        }
    }


Edit AccordionTableViewController.swift 

👍

**Comment by tadija** [comment]
There's no built in way for this, but might be a good idea for enhancement.

**Comment by Nachot93** [comment]
`collapseCell` and `expandCell` throw 

> 'collapseCell' is inaccessible due to 'private' protection level

**Comment by Nachot93** [comment]
Hello?

**Comment by iStorry** [comment]
@Nachot93 please follow this

> > ```
> > open func toggleCell(_ cell: AccordionTableViewCell, animated: Bool) {
> > ```
> 
> ```
>     if cell.expanded {
>         collapseCell(cell, animated: animated)
>     } else {
>         if expandedIndexPaths.count > 0 {
>             for i in 0 ..< expandedIndexPaths.count {
>                 if let cellPath = tableView.cellForRow(at: self.expandedIndexPaths[i]) {
>                     collapseCell(cellPath as! AccordionTableViewCell, animated: animated)
>                 }
>             }
>         }
>         expandCell(cell, animated: animated)
>     }
> }
> ```
> 
> Edit AccordionTableViewController.swift
> 
> 👍

**Comment by iStorry** [comment]
@Nachot93 you can change function to public or open 

https://github.com/tadija/AEAccordion/blob/master/Sources/AEAccordion/AccordionTableViewController.swift#L98

https://github.com/tadija/AEAccordion/blob/master/Sources/AEAccordion/AccordionTableViewController.swift#L72
